// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-commons/tree/main/paramgen

package benthos

import (
	"github.com/conduitio/conduit-commons/config"
)

const (
	ProcessorConfigBenthosYAML = "benthosYAML"
)

func (ProcessorConfig) Parameters() map[string]config.Parameter {
	return map[string]config.Parameter{
		ProcessorConfigBenthosYAML: {
			Default:     "",
			Description: "BenthosYAML is the YAML configuration for the Benthos pipeline",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
	}
}
