// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-commons/tree/main/paramgen

package benthos

import (
	"github.com/conduitio/conduit-commons/config"
)

const (
	BenthosConfigBatchSize         = "batchSize"
	BenthosConfigChannelBufferSize = "channelBufferSize"
	BenthosConfigThreadCount       = "threadCount"
	BenthosConfigYaml              = "yaml"
)

func (BenthosConfig) Parameters() map[string]config.Parameter {
	return map[string]config.Parameter{
		BenthosConfigBatchSize: {
			Default:     "100",
			Description: "BatchSize controls the maximum number of records to process in a single Benthos batch\nHigher values can improve throughput but may increase memory usage",
			Type:        config.ParameterTypeInt,
			Validations: []config.Validation{
				config.ValidationGreaterThan{V: 0},
			},
		},
		BenthosConfigChannelBufferSize: {
			Default:     "10",
			Description: "ChannelBufferSize controls the size of internal channels for communication\nHigher values can improve throughput but use more memory",
			Type:        config.ParameterTypeInt,
			Validations: []config.Validation{},
		},
		BenthosConfigThreadCount: {
			Default:     "1",
			Description: "ThreadCount controls the number of parallel processing threads in the Benthos pipeline\nHigher values can improve throughput for CPU-bound processors",
			Type:        config.ParameterTypeInt,
			Validations: []config.Validation{},
		},
		BenthosConfigYaml: {
			Default:     "",
			Description: "YAML is the complete Benthos configuration (excluding input/output)\nThis includes processors, resources, buffer, metrics, etc.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
	}
}
